"""empty message

Revision ID: 46385aac497c
Revises: 
Create Date: 2021-02-03 00:58:15.107385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46385aac497c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('investment_lists_id', sa.Integer(), nullable=False),
    sa.Column('investment_properties_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investment_lists_id'], ['investment_lists.id'], ),
    sa.ForeignKeyConstraint(['investment_properties_id'], ['investment_properties.id'], ),
    sa.PrimaryKeyConstraint('investment_lists_id', 'investment_properties_id')
    )
    op.drop_table('rentals')
    op.drop_table('rental_lists')
    op.drop_table('tenants')
    op.add_column('investment_lists', sa.Column('list_name', sa.Text(), nullable=True))
    op.drop_column('investment_lists', 'investment_properties')
    op.drop_column('investment_lists', 'name')
    op.drop_column('investment_properties', 'investment_list_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_properties', sa.Column('investment_list_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('investment_lists', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('investment_lists', sa.Column('investment_properties', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('investment_lists', 'list_name')
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('untitled_table_id_seq'::regclass)"), nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tenants_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rental_lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rentals', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='tenant_id'),
    sa.PrimaryKeyConstraint('id', name='rental_lists_pkey')
    )
    op.create_table('rentals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rental_list_id', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rental_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
